name: it-command
on:
  repository_dispatch:
    types: [it-command]
    
jobs:
  example:
    runs-on: ubuntu-20.04
    env:
      PR_NUMBER: ${{ github.event.client_payload.github.payload.issue.number }}
      PR_P: ${{ github.event.issue.number }}
    steps:
      - name: Create URL to the run output
        id: vars
        run: echo ::set-output name=run-url::https://github.com/$GITHUB_REPOSITORY/actions/runs/$GITHUB_RUN_ID      
      - name: Update success comment
        uses: peter-evans/create-or-update-comment@v1
        with:
          comment-id: ${{ github.event.client_payload.github.payload.comment.id }}
          body: |
            > Action has been started. [Click here to see the action](${{ steps.vars.outputs.run-url }})
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: 'refs/pull/${{ env.PR_NUMBER }}/merge'
      - name: Set up JDK 7
        uses: actions/setup-java@v1
        with:
          java-version: 7
      - name: Set up JDK 9
        uses: actions/setup-java@v1
        with:
          java-version: 9
      - name: Set JAVA_HOME
        run: |
          echo "JAVA_7_HOME=$JAVA_HOME_7_0_312_X64" >> $GITHUB_ENV
          echo "JAVA_8_HOME=$JAVA_HOME_8_X64" >> $GITHUB_ENV
          echo "JAVA_9_HOME=$JAVA_HOME_9_0_7_X64" >> $GITHUB_ENV
          echo "JAVA_HOME=$JAVA_HOME_8_X64" >> $GITHUB_ENV
      - name: Java Environment
        run: env | grep '^JAVA'
      - name: Cache Maven packages
        uses: actions/cache@v2
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2
      - name: Cache node modules
        uses: actions/cache@v2
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-node-modules-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-modules-
      - name: Cache node install
        uses: actions/cache@v2
        with:
          path: 'node_install'
          key: ${{ runner.os }}-node_install-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-node_install-
      - name: Build with Maven
        run: ./mvnw --batch-mode -Pit-module -DskipTests clean install
      - name: Integration Test
        working-directory: ./plugins-it
        run: ../mvnw --batch-mode clean install -Pit-module -pl ${{ github.event.client_payload.slash_command.args.all }}
      - name: Reports 
        id: vars1
        working-directory: ./plugins-it
        run: echo ::set-output name=report::"$(cat ./*/target/failsafe-reports/*.txt | grep ^Tests)"
      - name: Update  comment
        uses: peter-evans/create-or-update-comment@v1
        with:
          comment-id: ${{ github.event.client_payload.github.payload.comment.id }}
          body: |
            > ${{ steps.vars1.outputs.report }}
        
